apiVersion: v1
kind: ConfigMap
metadata:
  name: vchat-config
data:
  local.yaml: |
    mode: production
    public_url: "https://vchat.example.com"
    allowed_origins:
      - "https://vchat.example.com"
    trusted_proxy_cidrs: []
    cookie_domain: "vchat.example.com"
    cookie_secure: true
    enable_https_middleware: true
    auth_session_idle_timeout_seconds: 14400
    admin_user_create_enabled: true

    redis_uri: "redis://redis.vchat.svc.cluster.local:6379/30"
    database_uri: !env "$DATABASE_URI"
    celery_redis_uri: "redis://redis.vchat.svc.cluster.local:6379/"
    celery_broker_db: 31
    celery_backend_db: 32

    request_embedding_concurrency: 1
    request_embedding_queue_timeout_seconds: 20
    request_embedding_queue_warn_seconds: 1
    embedding_service_url: !env "$EMBEDDING_SERVICE_URL"
    embedding_service_timeout_seconds: 30

    log_format: "json"
    openai_api_key: !env "$OPENAI_API_KEY"
    gigachat_api_key: !env "$GIGACHAT_API_KEY"
    secret_key: !env "$SECRET_KEY"
    cookie_key: !env "$COOKIE_KEY"
