apiVersion: v1
kind: ConfigMap
metadata:
  name: vchat-config
data:
  local.yaml: |
    mode: production
    public_url: "https://vchat.example.com"
    public_cdn: "https://vchat.example.com"
    allowed_origins:
      - "https://vchat.example.com"
    cookie_domain: "vchat.example.com"
    cookie_secure: true
    enable_https_middleware: true

    redis_uri: "redis://redis.vchat.svc.cluster.local:6379/30"
    database_uri: !env "$DATABASE_URI"
    celery_redis_uri: "redis://redis.vchat.svc.cluster.local:6379/"
    celery_broker_db: 31
    celery_backend_db: 32

    log_format: "json"
    openai_api_key: !env "$OPENAI_API_KEY"
    gigachat_api_key: !env "$GIGACHAT_API_KEY"
    secret_key: !env "$VCHAT_SECRET_KEY"
    cookie_key: !env "$VCHAT_COOKIE_KEY"
