apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vchat

resources:
  - namespace.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - service.yaml
  - ingress.yaml
  - deployment-web.yaml
  - deployment-celery.yaml
  - deployment-celery-beat.yaml
  - job-migrate.yaml
  - hpa-web.yaml
  - networkpolicy.yaml

images:
  - name: vchat
    newName: registry.example.com/vchat
    newTag: latest
