server {
    listen 80;
    listen [::]:80;
    server_name vchat.dzen.dev;

    location /.well-known/acme-challenge/ {
        root /var/www/vchat/acme;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
