"""refactor notify to use normalized table

Revision ID: 1e8f5b724eb0
Revises: ba55c31ea6bf
Create Date: 2025-12-08 00:41:57.206837

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1e8f5b724eb0"
down_revision = "ba55c31ea6bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notify_read",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notify_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["notify_id"], ["notify.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("notify_id", "user_id", name="uq_notify_read_user"),
    )
    op.create_index(
        op.f("ix_notify_read_notify_id"), "notify_read", ["notify_id"], unique=False
    )
    op.create_index(
        op.f("ix_notify_read_user_id"), "notify_read", ["user_id"], unique=False
    )
    op.add_column(
        "notify", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_column("notify", "read_by")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notify",
        sa.Column(
            "read_by",
            postgresql.ARRAY(sa.INTEGER()),
            server_default=sa.text("'{}'::integer[]"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("notify", "updated_at")
    op.drop_index(op.f("ix_notify_read_user_id"), table_name="notify_read")
    op.drop_index(op.f("ix_notify_read_notify_id"), table_name="notify_read")
    op.drop_table("notify_read")
    # ### end Alembic commands ###
