"""audio records

Revision ID: 2c09d70ea753
Revises: d3f0c4f2e825
Create Date: 2025-11-23 04:37:25.149320

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2c09d70ea753"
down_revision = "d3f0c4f2e825"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    chat_type = postgresql.ENUM("chat", "call", name="chattype")
    bind = op.get_bind()
    chat_type.create(bind, checkfirst=True)

    op.add_column(
        "chat",
        sa.Column(
            "type",
            chat_type,
            nullable=False,
            server_default=sa.text("'chat'::chattype"),
        ),
    )
    op.add_column(
        "chat",
        sa.Column(
            "record",
            sa.Text(),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column("chat", "type", server_default=None, existing_type=chat_type)
    op.alter_column("chat", "record", server_default=None, existing_type=sa.Text())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat", "record")
    op.drop_column("chat", "type")
    chat_type = postgresql.ENUM("chat", "call", name="chattype")
    chat_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
