"""chunk cascade

Revision ID: 3a8951a7d487
Revises: 83562e51e8de
Create Date: 2025-11-30 04:11:41.246451

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "3a8951a7d487"
down_revision = "83562e51e8de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chunk_document_id_fkey", "chunk", type_="foreignkey")
    op.drop_constraint("chunk_chat_id_fkey", "chunk", type_="foreignkey")
    op.create_foreign_key(
        None, "chunk", "document", ["document_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "chunk", "chat", ["chat_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chunk", type_="foreignkey")
    op.drop_constraint(None, "chunk", type_="foreignkey")
    op.create_foreign_key("chunk_chat_id_fkey", "chunk", "chat", ["chat_id"], ["id"])
    op.create_foreign_key(
        "chunk_document_id_fkey", "chunk", "document", ["document_id"], ["id"]
    )
    # ### end Alembic commands ###
