"""restore_post_tag

Revision ID: 69257362857f
Revises: 779b023fc888
Create Date: 2025-11-27 23:32:10.835352

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "69257362857f"
down_revision = "779b023fc888"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=140), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("post_category_id", sa.Integer(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_category_id"],
            ["post_category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_post_tag_post_id"), "post_tag", ["post_id"], unique=False)
    op.create_index(op.f("ix_post_tag_tag"), "post_tag", ["tag"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_tag_tag"), table_name="post_tag")
    op.drop_index(op.f("ix_post_tag_post_id"), table_name="post_tag")
    op.drop_table("post_tag")
    # ### end Alembic commands ###
