"""add used_chunks to chat_msg

Revision ID: 779b023fc888
Revises: 2c09d70ea753
Create Date: 2025-11-25 02:07:35.621386

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "779b023fc888"
down_revision = "2c09d70ea753"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_msg",
        sa.Column(
            "used_chunks", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_msg", "used_chunks")
    # ### end Alembic commands ###
