"""tokens

Revision ID: 7b2298768de2
Revises: 69257362857f
Create Date: 2025-11-30 01:36:45.440629

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b2298768de2"
down_revision = "69257362857f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_msg",
        sa.Column("tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_msg", "tokens")
    # ### end Alembic commands ###
