"""data

Revision ID: 8e870215bf5f
Revises: 09619a4b8f9c
Create Date: 2025-11-16 23:53:18.978753

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = "8e870215bf5f"
down_revision = "09619a4b8f9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent;")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=62), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("user_uid", sa.String(length=256), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_project_id"), "chat", ["project_id"], unique=False)
    op.create_index(op.f("ix_chat_user_uid"), "chat", ["user_uid"], unique=False)
    op.create_table(
        "project_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("owner", "member", name="projectrole"),
            nullable=False,
        ),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("site", "s3", "custom", name="sourcetype"),
            nullable=False,
        ),
        sa.Column("uri", sa.String(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_project_id"), "source", ["project_id"], unique=False
    )
    op.create_table(
        "chat_msg",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("full_context", sa.Text(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("system", "user", "assistant", name="chatrole"),
            nullable=False,
        ),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_uid", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_msg_chat_id"), "chat_msg", ["chat_id"], unique=False)
    op.create_index(
        op.f("ix_chat_msg_user_uid"), "chat_msg", ["user_uid"], unique=False
    )
    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uri", sa.String(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("lang", sa.String(length=2), nullable=False),
        sa.Column("length", sa.Integer(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status", postgresql.ENUM("added", "indexed", name="status"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_source_id"), "document", ["source_id"], unique=False
    )
    op.create_index(op.f("ix_document_status"), "document", ["status"], unique=False)
    op.create_table(
        "chunk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("user_uid", sa.String(length=256), nullable=False),
        sa.Column("msg_id", sa.Integer(), nullable=True),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("chunk_ix", sa.Integer(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tsv", postgresql.TSVECTOR(), nullable=True),
        sa.Column("embedding", Vector(dim=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["msg_id"],
            ["chat_msg.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chunk_chat_id"), "chunk", ["chat_id"], unique=False)
    op.create_index(
        op.f("ix_chunk_document_id"), "chunk", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_chunk_msg_id"), "chunk", ["msg_id"], unique=False)
    op.create_index(op.f("ix_chunk_user_uid"), "chunk", ["user_uid"], unique=False)
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "users", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )

    op.execute("""
    CREATE OR REPLACE FUNCTION chunk_tsv_update() RETURNS trigger AS $$
    DECLARE
    txt text := coalesce(NEW.content, '');
    BEGIN
    NEW.tsv :=
        to_tsvector('russian', txt)
        || to_tsvector('english', txt);
    RETURN NEW;
    END
    $$ LANGUAGE plpgsql;""")

    op.execute("""DROP TRIGGER IF EXISTS chunk_tsv_trigger ON chunk;""")
    op.execute("""CREATE TRIGGER chunk_tsv_trigger
    BEFORE INSERT OR UPDATE OF content
    ON chunk
    FOR EACH ROW EXECUTE FUNCTION chunk_tsv_update();""")

    op.execute("""-- HNSW index for cosine similarity on embeddings
    CREATE INDEX IF NOT EXISTS chunk_embedding_cosine
    ON chunk
    USING hnsw (embedding vector_cosine_ops);""")

    op.execute("""-- GIN index for full-text search
    CREATE INDEX IF NOT EXISTS chunk_tsv_gin
    ON chunk USING GIN (tsv);
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop raw SQL indexes
    op.execute("DROP INDEX IF EXISTS chunk_embedding_cosine;")
    op.execute("DROP INDEX IF EXISTS chunk_tsv_gin;")

    # Drop trigger and function
    op.execute("DROP TRIGGER IF EXISTS chunk_tsv_trigger ON chunk;")
    op.execute("DROP FUNCTION IF EXISTS chunk_tsv_update();")

    # Drop enums
    op.execute("DROP TYPE IF EXISTS projectrole;")
    op.execute("DROP TYPE IF EXISTS sourcetype;")
    op.execute("DROP TYPE IF EXISTS chatrole;")
    op.execute("DROP TYPE IF EXISTS status;")

    # Drop extensions
    op.execute("DROP EXTENSION IF EXISTS vector;")
    op.execute("DROP EXTENSION IF EXISTS unaccent;")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_index(op.f("ix_chunk_user_uid"), table_name="chunk")
    op.drop_index(op.f("ix_chunk_msg_id"), table_name="chunk")
    op.drop_index(op.f("ix_chunk_document_id"), table_name="chunk")
    op.drop_index(op.f("ix_chunk_chat_id"), table_name="chunk")
    op.drop_table("chunk")
    op.drop_index(op.f("ix_document_status"), table_name="document")
    op.drop_index(op.f("ix_document_source_id"), table_name="document")
    op.drop_table("document")
    op.drop_index(op.f("ix_chat_msg_user_uid"), table_name="chat_msg")
    op.drop_index(op.f("ix_chat_msg_chat_id"), table_name="chat_msg")
    op.drop_table("chat_msg")
    op.drop_index(op.f("ix_source_project_id"), table_name="source")
    op.drop_table("source")
    op.drop_table("project_user")
    op.drop_index(op.f("ix_chat_user_uid"), table_name="chat")
    op.drop_index(op.f("ix_chat_project_id"), table_name="chat")
    op.drop_table("chat")
    op.drop_table("project")
    # ### end Alembic commands ###
