"""add_short_id

Revision ID: 9badd855953b
Revises: 7b2298768de2
Create Date: 2025-11-30 02:07:13.087611

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9badd855953b"
down_revision = "7b2298768de2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat", sa.Column("short_id", sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, "chat", ["short_id"])
    op.add_column(
        "document", sa.Column("short_id", sa.String(length=20), nullable=True)
    )
    op.create_unique_constraint(None, "document", ["short_id"])
    op.alter_column(
        "post", "short_id", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.add_column("project", sa.Column("short_id", sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, "project", ["short_id"])
    op.add_column("source", sa.Column("short_id", sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, "source", ["short_id"])

    # Create triggers and backfill
    for table in ["chat", "document", "project", "source"]:
        op.execute(f"""
            CREATE TRIGGER set_short_id
            BEFORE INSERT OR UPDATE
            ON public.{table}
            FOR EACH ROW
            EXECUTE FUNCTION public.trigger_set_short_id();
        """)

        # Backfill existing records
        op.execute(f"""
            UPDATE public.{table}
            SET short_id = sqids.encode(array[id], 'xMXvWAEb78OqjrtGKwzhT51aFeLmuQ9PJsNSi24BgYdfn6HVoZ0pkUy3RDCclI', 10)
            WHERE short_id IS NULL;
        """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ["chat", "document", "project", "source"]:
        op.execute(f"DROP TRIGGER IF EXISTS set_short_id ON public.{table}")

    op.drop_constraint(None, "source", type_="unique")
    op.drop_column("source", "short_id")
    op.drop_constraint(None, "project", type_="unique")
    op.drop_column("project", "short_id")
    op.alter_column(
        "post", "short_id", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.drop_constraint(None, "document", type_="unique")
    op.drop_column("document", "short_id")
    op.drop_constraint(None, "chat", type_="unique")
    op.drop_column("chat", "short_id")
    # ### end Alembic commands ###
