"""titles prompts

Revision ID: ee439cbc3357
Revises: 8d1e1a6a75e6
Create Date: 2025-11-22 21:43:52.347657

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee439cbc3357"
down_revision = "8d1e1a6a75e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("title", sa.String(), nullable=True))
    op.add_column("document", sa.Column("is_ignored", sa.Boolean(), nullable=False))
    op.add_column("project", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("project", sa.Column("system_prompt", sa.Text(), nullable=True))
    op.add_column("project", sa.Column("agent_style", sa.String(), nullable=True))
    op.add_column("source", sa.Column("title", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source", "title")
    op.drop_column("project", "agent_style")
    op.drop_column("project", "system_prompt")
    op.drop_column("project", "description")
    op.drop_column("document", "is_ignored")
    op.drop_column("document", "title")
    # ### end Alembic commands ###
