"""Add google_drive source type

Revision ID: fd5ec2ad7aba
Revises: 5f74f0854dde
Create Date: 2025-12-01 22:55:44.660700

"""

# revision identifiers, used by Alembic.
revision = "fd5ec2ad7aba"
down_revision = "5f74f0854dde"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
