apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vchat

resources:
  - ../base
  - postgres.yaml
  - redis.yaml
  - secret.yaml

images:
  - name: registry.example.com/vchat
    newName: vchat
    newTag: k8s-local

replicas:
  - name: vchat-web
    count: 1
  - name: vchat-celery
    count: 1
  - name: vchat-celery-beat
    count: 1
  - name: vchat-embedder
    count: 1

patches:
  - path: configmap.yaml
  - path: patch-local-overrides.yaml
