DEFAULT_CRAWLER_USER_AGENT = (
    "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15.0) "
    "Gecko/20100101 Firefox/15.0.1 vChat Crawler"
)
DEFAULT_CRAWLER_CONCURRENT_REQUESTS = 16
DEFAULT_CRAWLER_DOWNLOAD_DELAY = 0.0

REINDEX_PERIOD_WEEKLY = "weekly"
REINDEX_PERIOD_MONTHLY = "monthly"
REINDEX_PERIOD_MANUAL = "manual"

REINDEX_PERIOD_CHOICES = (
    (REINDEX_PERIOD_WEEKLY, "Еженедельная"),
    (REINDEX_PERIOD_MONTHLY, "Ежемесячная"),
    (REINDEX_PERIOD_MANUAL, "Ручная"),
)

REINDEX_PERIOD_TO_DAYS = {
    REINDEX_PERIOD_WEEKLY: 7,
    REINDEX_PERIOD_MONTHLY: 30,
}
