"""Русские пользовательские тексты без i18n/gettext."""

from __future__ import annotations

from typing import Any

RU: dict[str, str] = {
    "Title": "Заголовок",
    "Welcome to vchat": "Добро пожаловать в vchat",
    "Prices": "Тарифы",
    "Closed": "Закрыто",
    "Reopened": "Открыто снова",
    "Error {code}": "Ошибка {code}",
    "Admin Dashboard": "Панель администратора",
    "User List": "Список пользователей",
    "Invalid code": "Неверный код",
    "Login to vchat": "Вход в vchat",
    "Logout from vchat": "Выход из vchat",
    "Register on vchat": "Регистрация в vchat",
    "Confirm registration": "Подтверждение регистрации",
    "Recover password": "Восстановление пароля",
    "Resend registration code": "Повторная отправка кода регистрации",
    "Reset password": "Сброс пароля",
    "Email or password is incorrect": "Неверный email или пароль",
    "Wrong email or password": "Неверный email или пароль",
    "CAPTCHA error": "Ошибка CAPTCHA",
    "This email is already in use, log in to the site using your email": "Этот email уже используется, войдите с ним на сайт",
    "User not found": "Пользователь не найден",
    "Email already confirmed. Log in to the site or recover password": "Email уже подтвержден. Войдите на сайт или восстановите пароль",
    "Activation code expired": "Срок действия кода активации истек",
    "Activation code error, seems broken": "Ошибка кода активации",
    "Unknown error": "Неизвестная ошибка",
    "Password changed": "Пароль изменен",
    "Registration confirmation": "Подтверждение регистрации",
    "Password reset": "Сброс пароля",
    "Repeat registration confirmation": "Повторное подтверждение регистрации",
    "User settings": "Настройки пользователя",
    "Settings are saved": "Настройки сохранены",
    "Data": "Данные",
    "Settings": "Настройки",
    "Sources": "Источники",
    "Edit Source": "Редактирование источника",
    "Topics": "Темы",
    "Stats": "Статистика",
    "Chat": "Чат",
    "Integration": "Интеграция",
    "Chat Widget": "Виджет чата",
    "Files": "Файлы",
    "Settings updated": "Настройки обновлены",
    "Source updated": "Источник обновлен",
    "Topics updated": "Темы обновлены",
    "Topics generation started in background": "Генерация тем запущена в фоне",
    "Crawl task started for source": "Задача обхода источника запущена",
    "Update task started": "Задача обновления запущена",
    "Crawl task started for all sources": "Задача обхода всех источников запущена",
    "Full rebuild task started": "Полная переиндексация запущена",
    "Upload index rebuild started": "Переиндексация загруженных файлов запущена",
    "Update task started for %(title)s": "Задача обновления запущена для %(title)s",
    "Chats": "Чаты",
    "Chat History": "История чатов",
    "Previous": "Назад",
    "Next": "Вперед",
    "Close": "Закрыть",
    "Search": "Поиск",
    "Search by": "Поиск по",
    "Showing": "Показано",
    "starting from": "начиная с",
    "of": "из",
    "entries": "записей",
    "Toggle Theme": "Сменить тему",
    "Navbar": "Навигация",
    "Toggle left menu": "Переключить левое меню",
    "Profile": "Профиль",
    "Logout": "Выйти",
    "Home": "Главная",
    "Dashboard": "Панель",
    "Login": "Вход",
    "Close sidebar": "Закрыть боковую панель",
    "Open sidebar": "Открыть меню",
    "Toggle sidebar hover": "Переключить режим боковой панели",
    "Toggle layout sidebar": "Переключить боковую панель",
    "Dense layout sidebar": "Компактная боковая панель",
    "Realtime": "Реальное время",
    "User Chats": "Чаты пользователей",
    "Workspace": "Рабочее пространство",
    "User": "Пользователь",
    "Admin area": "Админ-зона",
    "Users": "Пользователи",
    "Back to app": "Назад в приложение",
    "vchat Logo": "Логотип vchat",
    "🍪 We use cookies on this site to analyze traffic, save preferences, and optimize performance..": "🍪 Мы используем cookies для аналитики, сохранения настроек и оптимизации работы сайта.",
    "More info": "Подробнее",
    "Accept": "Принять",
    "&copy; 2025 vchat. All rights reserved.": "&copy; 2025 vchat. Все права защищены.",
    "© 2025 vchat. All rights reserved": "© 2025 vchat. Все права защищены",
    "Login to your account": "Войти в аккаунт",
    "To get access to your projects use this login form.": "Чтобы получить доступ к проектам, используйте форму входа.",
    "Email address": "Email",
    "Password": "Пароль",
    "Form validation error": "Ошибка валидации формы",
    "Update your profile details.": "Обновите данные профиля.",
    "Save settings": "Сохранить настройки",
    "Name": "Имя",
    "Your email": "Ваш email",
    "Your password": "Ваш пароль",
    "Length from 6 to 254 characters": "Длина от 6 до 254 символов",
    "Length from 4 to 35 characters": "Длина от 4 до 35 символов",
    "Length from 4 to 100 characters": "Длина от 4 до 100 символов",
    "Length from 6 to 35 characters": "Длина от 6 до 35 символов",
    "Enter a valid email": "Введите корректный email",
    "Required field": "Обязательное поле",
    "name@company.com": "name@company.com",
    "Confirm password": "Подтвердите пароль",
    "Password confirmation": "Подтверждение пароля",
    "Passwords must match": "Пароли должны совпадать",
    "Accept site terms and conditions": "Я принимаю условия использования сайта",
    "You must accept the terms of use of the site": "Необходимо принять условия использования сайта",
    "New password": "Новый пароль",
    "New password (repeat)": "Новый пароль (повтор)",
    "Confirm new password": "Подтвердите новый пароль",
    "Current password": "Текущий пароль",
    "Change password": "Смена пароля",
    "Keep your account secure by updating your password regularly.": "Обновляйте пароль регулярно для безопасности аккаунта.",
    "Save password": "Сохранить пароль",
    "Need to update your profile details instead?": "Нужно изменить данные профиля?",
    "Go to settings": "Перейти в настройки",
}


def _(message: str, *args: Any, **kwargs: Any) -> str:
    text = RU.get(message, message)
    if kwargs:
        try:
            return text % kwargs
        except Exception:
            try:
                return text.format(**kwargs)
            except Exception:
                return text
    if args:
        try:
            return text % args
        except Exception:
            return text
    return text
